// SPDX-License-Identifier: MIT
pragma solidity 0.8.28;

import {Vm} from "forge-std/Test.sol";
import {ExpiryCalendar} from "../../../src/v2/ExpiryCalendar.sol";
import {IExpiryCalendar} from "../../../src/v2/interfaces/IExpiryCalendar.sol";
import {V2Errors} from "../../../src/v2/interfaces/V2Errors.sol";
import {V8Roles} from "../../../src/v2/access/V8Roles.sol";
import {V8AccessTest} from "../lib/V8Access.sol";

/// @notice ExpiryCalendar: the 16:00 New York grid, DST switches, holidays, weeklies, special expiries, the regular
///         session, the bounded next-expiry search and the admin surface.
/// @dev Three independent references keep the contract's date maths honest:
///        - test/v2/fixtures/expiries.json, generated by gen-expiries.mjs from node's Intl tz database (America/New_York),
///          125 instants 2026-2030 with every read's expected answer;
///        - a closed-form US DST rule and a leap-year count written below that share no code with Hinnant's
///          algorithm, fuzzed over 2007-2099;
///        - hand-written instants for the cases the task names (each commented with its New York wall time).
///      The calendar is seeded exactly like the launch deploy: the NYSE 2026-2028 full-day closures from the F2-02
///      recon (callhouse ops/markets/v2-sources.json `nyseHolidays`, copied into the fixture's `holidayDayIndexes`).
///      Setup is self-contained until C2-08 consolidates the v2 test base.
contract ExpiryCalendarTest is V8AccessTest {
    string internal constant FIXTURE = "test/v2/fixtures/expiries.json";

    uint256 internal constant DAY = 86_400;
    int32 internal constant EDT = -14_400;
    int32 internal constant EST = -18_000;

    /// @dev Day indexes: 2007-01-01 (first year of the current US DST rule), 2100-01-01 (the closed form below stops
    ///      being valid: 2100 is not a leap year), the last day a uint40 timestamp reaches, and a known Monday.
    uint256 internal constant DAY_2007 = 13_514;
    uint256 internal constant DAY_2100 = 47_482;
    uint256 internal constant DAY_MAX = 12_725_829;
    uint256 internal constant MONDAY_2026_09_21 = 20_717;
    /// @dev Leap days in years 1 .. 1969: 1969 / 4 - 1969 / 100 + 1969 / 400.
    uint256 internal constant LEAPS_BEFORE_1970 = 477;

    // Named instants, unix seconds (New York wall time in the comment; all cross-checked by node Intl).
    uint40 internal constant WED_0916_0929_59 = 1_789_565_399; // 2026-09-16 09:29:59 EDT
    uint40 internal constant WED_0916_0930 = 1_789_565_400; // 2026-09-16 09:30:00 EDT
    uint40 internal constant WED_0916_1559_59 = 1_789_588_799; // 2026-09-16 15:59:59 EDT
    uint40 internal constant WED_0916_CLOSE = 1_789_588_800; // 2026-09-16 16:00:00 EDT
    uint40 internal constant FRI_0918_CLOSE = 1_789_761_600; // 2026-09-18 16:00:00 EDT
    uint40 internal constant SAT_0919_NOON = 1_789_833_600; // 2026-09-19 12:00:00 EDT
    uint40 internal constant SAT_0919_1600 = 1_789_848_000; // 2026-09-19 16:00:00 EDT
    // T-479 special-expiry windows. Derived with Python zoneinfo America/New_York, not by hand.
    uint40 internal constant WED_0916_0959_59 = 1_789_567_199; // 2026-09-16 09:59:59 EDT: window opens 09:29:59
    uint40 internal constant WED_0916_1000 = 1_789_567_200; // 2026-09-16 10:00:00 EDT: window opens 09:30:00
    uint40 internal constant WED_0916_1600_01 = 1_789_588_801; // 2026-09-16 16:00:01 EDT: window ends after close
    uint40 internal constant FRI_0918_NOON = 1_789_747_200; // 2026-09-18 12:00:00 EDT
    uint40 internal constant SUN_0920_1600 = 1_789_934_400; // 2026-09-20 16:00:00 EDT, BUG-04 F3's witness
    uint40 internal constant WED_1202_0959_59 = 1_796_223_599; // 2026-12-02 09:59:59 EST
    uint40 internal constant WED_1202_1000 = 1_796_223_600; // 2026-12-02 10:00:00 EST
    uint40 internal constant MON_0921_CLOSE = 1_790_020_800; // 2026-09-21 16:00:00 EDT
    uint40 internal constant FRI_0925_CLOSE = 1_790_366_400; // 2026-09-25 16:00:00 EDT
    uint40 internal constant MON_0928_CLOSE = 1_790_625_600; // 2026-09-28 16:00:00 EDT
    uint40 internal constant FRI_1002_CLOSE = 1_790_971_200; // 2026-10-02 16:00:00 EDT
    uint40 internal constant FRI_1009_CLOSE = 1_791_576_000; // 2026-10-09 16:00:00 EDT

    uint40 internal constant WED_1202_0929_59 = 1_796_221_799; // 2026-12-02 09:29:59 EST
    uint40 internal constant WED_1202_0930 = 1_796_221_800; // 2026-12-02 09:30:00 EST
    uint40 internal constant WED_1202_1559_59 = 1_796_245_199; // 2026-12-02 15:59:59 EST
    uint40 internal constant WED_1202_CLOSE = 1_796_245_200; // 2026-12-02 16:00:00 EST

    uint40 internal constant FRI_0306_CLOSE = 1_772_830_800; // 2026-03-06 16:00:00 EST (21:00 UTC)
    uint40 internal constant SUN_0308_0159_59 = 1_772_953_199; // 2026-03-08 01:59:59 EST
    uint40 internal constant SUN_0308_0300 = 1_772_953_200; // 2026-03-08 03:00:00 EDT (the next second)
    uint40 internal constant MON_0309_CLOSE = 1_773_086_400; // 2026-03-09 16:00:00 EDT (20:00 UTC)
    uint40 internal constant FRI_0313_CLOSE = 1_773_432_000; // 2026-03-13 16:00:00 EDT

    uint40 internal constant FRI_1030_CLOSE = 1_793_390_400; // 2026-10-30 16:00:00 EDT (20:00 UTC)
    uint40 internal constant SUN_1101_0159_59 = 1_793_512_799; // 2026-11-01 01:59:59 EDT
    uint40 internal constant SUN_1101_0100_EST = 1_793_512_800; // 2026-11-01 01:00:00 EST (the next second)
    uint40 internal constant MON_1102_CLOSE = 1_793_653_200; // 2026-11-02 16:00:00 EST (21:00 UTC)
    uint40 internal constant FRI_1106_CLOSE = 1_793_998_800; // 2026-11-06 16:00:00 EST

    uint40 internal constant THU_0402_CLOSE = 1_775_160_000; // 2026-04-02 16:00:00 EDT
    uint40 internal constant GOOD_FRI_0403_CLOSE = 1_775_246_400; // 2026-04-03 16:00:00 EDT, holiday
    uint40 internal constant MON_0406_CLOSE = 1_775_505_600; // 2026-04-06 16:00:00 EDT
    uint40 internal constant WED_0701_CLOSE = 1_782_936_000; // 2026-07-01 16:00:00 EDT
    uint40 internal constant THU_0702_CLOSE = 1_783_022_400; // 2026-07-02 16:00:00 EDT
    uint40 internal constant MON_0706_CLOSE = 1_783_368_000; // 2026-07-06 16:00:00 EDT
    uint40 internal constant FRI_0710_CLOSE = 1_783_713_600; // 2026-07-10 16:00:00 EDT

    uint40 internal constant MON_1123_CLOSE = 1_795_467_600; // 2026-11-23 16:00:00 EST
    uint40 internal constant TUE_1124_0900 = 1_795_528_800; // 2026-11-24 09:00:00 EST
    uint40 internal constant TUE_1124_CLOSE = 1_795_554_000; // 2026-11-24 16:00:00 EST
    uint40 internal constant WED_1125_CLOSE = 1_795_640_400; // 2026-11-25 16:00:00 EST
    uint40 internal constant THANKSGIVING_1126_NOON = 1_795_712_400; // 2026-11-26 12:00:00 EST, holiday
    uint40 internal constant THANKSGIVING_1126_CLOSE = 1_795_726_800; // 2026-11-26 16:00:00 EST, holiday
    uint40 internal constant FRI_1127_1400 = 1_795_806_000; // 2026-11-27 14:00:00 EST, early-close day
    uint40 internal constant FRI_1127_CLOSE = 1_795_813_200; // 2026-11-27 16:00:00 EST

    uint40 internal constant THU_1224_CLOSE = 1_798_146_000; // 2026-12-24 16:00:00 EST, early-close day
    uint40 internal constant CHRISTMAS_1225_CLOSE = 1_798_232_400; // 2026-12-25 16:00:00 EST, holiday
    uint40 internal constant MON_1228_CLOSE = 1_798_491_600; // 2026-12-28 16:00:00 EST
    uint40 internal constant THU_1231_CLOSE = 1_798_750_800; // 2026-12-31 16:00:00 EST
    uint40 internal constant NEW_YEAR_0101_CLOSE = 1_798_837_200; // 2027-01-01 16:00:00 EST, holiday
    uint40 internal constant MON_0104_CLOSE = 1_799_096_400; // 2027-01-04 16:00:00 EST
    uint40 internal constant FRI_0108_CLOSE = 1_799_442_000; // 2027-01-08 16:00:00 EST

    uint40 internal constant THU_2027_1223_CLOSE = 1_829_595_600; // 2027-12-23 16:00:00 EST
    uint40 internal constant FRI_2027_1224_CLOSE = 1_829_682_000; // 2027-12-24 16:00:00 EST, holiday (observed)
    uint40 internal constant MON_2027_1227_CLOSE = 1_829_941_200; // 2027-12-27 16:00:00 EST
    uint40 internal constant FRI_2027_1231_CLOSE = 1_830_286_800; // 2027-12-31 16:00:00 EST
    uint40 internal constant MON_2028_0103_CLOSE = 1_830_546_000; // 2028-01-03 16:00:00 EST

    address internal admin = makeAddr("admin");
    address internal alice = makeAddr("alice");
    address internal bob = makeAddr("bob");

    ExpiryCalendar internal cal;

    function setUp() public {
        vm.warp(1_789_000_000);
        cal = _newCalendar(_seed(), admin);
    }

    /*//////////////////////////////////////////////////////////////
                                HELPERS
    //////////////////////////////////////////////////////////////*/

    /// @dev The fixture's holiday list, the launch seed.
    function _seed() internal view returns (uint32[] memory seed) {
        uint256[] memory raw = vm.parseJsonUintArray(vm.readFile(FIXTURE), ".holidayDayIndexes");
        seed = new uint32[](raw.length);
        for (uint256 i; i < raw.length; ++i) {
            assertLe(raw[i], type(uint32).max);
            // casting to 'uint32' is safe because the line above bounds it
            // forge-lint: disable-next-line(unsafe-typecast)
            seed[i] = uint32(raw[i]);
        }
    }

    function _days(uint256 from, uint256 count) internal pure returns (uint32[] memory list) {
        list = new uint32[](count);
        for (uint256 i; i < count; ++i) {
            // forge-lint: disable-next-line(unsafe-typecast)
            list[i] = uint32(from + i);
        }
    }

    function _close(uint32[] memory dayIndexes) internal {
        vm.prank(admin);
        cal.setHolidays(dayIndexes, true);
    }

    /// @dev Seeds `year` with one closure on its first Saturday, which no weekday read can see. Cases written for a
    ///      year with no closure (the fixture's 2029-2030, far-future fuzz weeks) need it now that the launch-shaped
    ///      calendar closes an unseeded year (SEC-48).
    function _markSeeded(uint256 year) internal {
        uint256 day = _refJan1(year);
        while (_refWeekday(day) != 5) ++day;
        _close(_days(day, 1));
    }

    /// @dev Reference for AN UNSEEDED YEAR FAILS CLOSED, sharing no code with the contract: the launch seed covers
    ///      2026-2028 and nothing else.
    function _refSeeded(uint256 day) internal pure returns (bool) {
        return day >= _refJan1(2026) && day < _refJan1(2029);
    }

    function _day(uint40 ts) internal pure returns (uint32) {
        // casting to uint32 is safe because a uint40 timestamp has fewer than 2^24 days
        // forge-lint: disable-next-line(unsafe-typecast)
        return uint32(ts / DAY);
    }

    function _expectNext(uint40 afterTs, bool weekly, uint40 expected, string memory why) internal view {
        assertEq(uint256(cal.nextExpiry(afterTs, weekly)), uint256(expected), why);
    }

    function _expectNoNext(uint40 afterTs, bool weekly) internal {
        vm.expectRevert(V2Errors.BadExpiry.selector);
        cal.nextExpiry(afterTs, weekly);
    }

    /// @dev ISO weekday, Monday = 0 ... Sunday = 6, anchored on a Monday read off a real calendar instead of on the
    ///      contract's "1970-01-01 was a Thursday". 7_000_000 is a multiple of 7 that keeps the subtraction positive.
    function _refWeekday(uint256 day) internal pure returns (uint256) {
        return (day + 7_000_000 - MONDAY_2026_09_21) % 7;
    }

    function _refIsLeap(uint256 year) internal pure returns (bool) {
        return (year % 4 == 0 && year % 100 != 0) || year % 400 == 0;
    }

    /// @dev Day index of January 1 of `year` (>= 1970): 365 a year plus the leap days counted directly.
    function _refJan1(uint256 year) internal pure returns (uint256) {
        uint256 y = year - 1;
        return (year - 1970) * 365 + (y / 4 - y / 100 + y / 400) - LEAPS_BEFORE_1970;
    }

    function _refYearOf(uint256 day) internal pure returns (uint256 year) {
        year = 1970 + day / 366;
        while (_refJan1(year + 1) <= day) ++year;
    }

    /// @dev The widely published closed form of the post-2007 US rule, valid 1900-2099: DST starts on March
    ///      14 - (1 + 5y/4) mod 7 at 02:00 EST (07:00 UTC) and ends on November 7 - (1 + 5y/4) mod 7 at 02:00 EDT
    ///      (06:00 UTC). Days before March 1 are 59 (+1 in a leap year), before November 1 304 (+1).
    function _refOffset(uint256 ts) internal pure returns (int32) {
        uint256 day = ts / DAY;
        uint256 year = _refYearOf(day);
        require(year >= 2007 && year <= 2099, "reference DST rule covers 2007-2099");
        uint256 k = (1 + year * 5 / 4) % 7;
        uint256 leap = _refIsLeap(year) ? 1 : 0;
        uint256 start = (_refJan1(year) + 59 + leap + (14 - k) - 1) * DAY + 7 hours;
        uint256 end = (_refJan1(year) + 304 + leap + (7 - k) - 1) * DAY + 6 hours;
        return ts >= start && ts < end ? EDT : EST;
    }

    /// @dev 16:00 New York of the date `day` per the reference rule (noon UTC is past either switch).
    function _refClose(uint256 day) internal pure returns (uint256) {
        return day * DAY + (_refOffset(day * DAY + 12 hours) == EDT ? 20 hours : 21 hours);
    }

    /*//////////////////////////////////////////////////////////////
                         FIXTURE (NODE INTL TABLE)
    //////////////////////////////////////////////////////////////*/

    function _key(uint256 i, string memory field) internal pure returns (string memory) {
        return string.concat(".cases[", vm.toString(i), "].", field);
    }

    /// @dev Every case of expiries.json: all five reads plus nextExpiry both ways (0 = must revert).
    ///      The fixture's 2029-2030 cases were generated as years with no closure whose weekdays trade (its Good Friday
    ///      2029 case says so). Under SEC-48 a year with no closure has no session days, so both years are marked
    ///      seeded first; what those cases then pin is a seeded year that misses a holiday, which still trades.
    ///      Launch pass: teach gen-expiries.mjs the rule and drop the two markers.
    function test_fixture_everyInstantMatchesIntl() public {
        _markSeeded(2029);
        _markSeeded(2030);
        string memory json = vm.readFile(FIXTURE);
        assertEq(vm.parseJsonUint(json, ".searchDays") * DAY, uint256(cal.NEXT_EXPIRY_SEARCH()), "search bound");
        uint256 n;
        while (vm.keyExistsJson(json, string.concat(".cases[", vm.toString(n), "]"))) {
            uint256 raw = vm.parseJsonUint(json, _key(n, "ts"));
            assertLe(raw, type(uint40).max);
            // forge-lint: disable-next-line(unsafe-typecast)
            uint40 ts = uint40(raw);
            string memory at = string.concat(
                vm.parseJsonString(json, _key(n, "local")), " | ", vm.parseJsonString(json, _key(n, "label"))
            );

            bool valid = vm.parseJsonBool(json, _key(n, "isValidExpiry"));
            assertEq(cal.isValidExpiry(ts), valid, string.concat("isValidExpiry ", at));
            assertEq(cal.isWeekly(ts), vm.parseJsonBool(json, _key(n, "isWeekly")), string.concat("isWeekly ", at));
            assertEq(
                cal.isRegularSession(ts),
                vm.parseJsonBool(json, _key(n, "isRegularSession")),
                string.concat("isRegularSession ", at)
            );
            assertEq(
                int256(cal.newYorkOffset(ts)),
                vm.parseJsonInt(json, _key(n, "newYorkOffset")),
                string.concat("newYorkOffset ", at)
            );
            if (valid) {
                assertEq(cal.closeOf(_day(ts)), ts, string.concat("closeOf ", at));
                assertTrue(cal.isSessionDay(_day(ts)), string.concat("isSessionDay ", at));
            }

            uint256 nextDaily = vm.parseJsonUint(json, _key(n, "nextDaily"));
            uint256 nextWeekly = vm.parseJsonUint(json, _key(n, "nextWeekly"));
            if (nextDaily == 0) _expectNoNext(ts, false);
            else assertEq(uint256(cal.nextExpiry(ts, false)), nextDaily, string.concat("nextExpiry daily ", at));
            if (nextWeekly == 0) _expectNoNext(ts, true);
            else assertEq(uint256(cal.nextExpiry(ts, true)), nextWeekly, string.concat("nextExpiry weekly ", at));
            ++n;
        }
        assertGe(n, 60, "expiries.json holds at least 60 instants");
    }

    /// @dev The seed is the recon's 29 full-day closures 2026-2028 (10 + 10 + 9), each one closed.
    function test_fixture_seedIsNyse2026To2028() public view {
        uint32[] memory seed = _seed();
        assertEq(seed.length, 29, "10 closures in 2026, 10 in 2027, 9 in 2028");
        assertEq(uint256(seed[0]), 20_454, "2026-01-01");
        assertEq(uint256(seed[28]), 21_543, "2028-12-25");
        for (uint256 i; i < seed.length; ++i) {
            assertTrue(cal.holiday(seed[i]));
            assertFalse(cal.isSessionDay(seed[i]));
            // forge-lint: disable-next-line(unsafe-typecast)
            assertFalse(cal.isValidExpiry(uint40(cal.closeOf(seed[i]))));
            assertGe(seed[i], _refJan1(2026));
            assertLt(seed[i], _refJan1(2029));
        }
        // Early closes are ordinary session days: the day after Thanksgiving 2026 and Christmas Eve 2026.
        assertTrue(cal.isValidExpiry(FRI_1127_CLOSE));
        assertTrue(cal.isValidExpiry(THU_1224_CLOSE));
    }

    /*//////////////////////////////////////////////////////////////
                              CONSTRUCTOR
    //////////////////////////////////////////////////////////////*/

    function test_constructor_seedsHolidaysEmitsAndGrantsAdmin() public {
        uint32[] memory seed = _seed();
        vm.recordLogs();
        ExpiryCalendar fresh = _newCalendar(seed, admin);
        Vm.Log[] memory logs = vm.getRecordedLogs();

        uint256 seen;
        for (uint256 i; i < logs.length; ++i) {
            if (logs[i].topics[0] != IExpiryCalendar.HolidaySet.selector) continue;
            assertEq(logs[i].emitter, address(fresh));
            assertEq(uint256(logs[i].topics[1]), uint256(seed[seen]), "indexed dayIndex, in seed order");
            assertEq(abi.decode(logs[i].data, (bool)), true);
            ++seen;
        }
        assertEq(seen, seed.length, "one HolidaySet per seeded day");
        (bool isMember,) = manager.hasRole(V8Roles.LISTING, admin);
        assertTrue(isMember, "LISTING is granted to admin, not the deployer");
        (bool deployerIs,) = manager.hasRole(V8Roles.LISTING, address(this));
        assertFalse(deployerIs, "the deployer gets nothing");
    }

    function test_constructor_emptySeedAndZeroAdmin() public {
        ExpiryCalendar bare = _newCalendar(new uint32[](0), admin);
        assertTrue(bare.isValidExpiry(GOOD_FRI_0403_CLOSE), "no seed: Good Friday is an ordinary Friday");

        // No seed makes no holiday claim, so no year is closed for want of one (SEC-48), and the mode is fixed at
        // construction: a closure set later does not switch it on for the other years.
        // forge-lint: disable-next-line(unsafe-typecast)
        uint40 fri2029 = uint40(bare.closeOf(uint32(_refJan1(2029) + 4)));
        assertTrue(bare.isValidExpiry(fri2029), "no seed: an unseeded 2029 Friday still trades");
        vm.prank(admin);
        bare.setHolidays(_days(_refJan1(2026), 1), true);
        assertTrue(bare.isValidExpiry(fri2029), "a later closure does not close the other years");

        vm.expectRevert(V2Errors.NoSource.selector);
        new ExpiryCalendar(address(0), new uint32[](0));
    }

    /*//////////////////////////////////////////////////////////////
                    AN UNSEEDED YEAR FAILS CLOSED (SEC-48)
    //////////////////////////////////////////////////////////////*/

    /// @dev The launch seed covers 2026-2028. A 2029 weekday is no session day, and the search from the last 2028
    ///      close runs into the closed year and reverts, both ways. POSITIVE CONTROL: seeding New Year's Day 2029
    ///      alone opens every other 2029 weekday and the same reads flip, so the refusals above are the year rule and
    ///      nothing else about those dates. Removing the year's only closure closes it again.
    function test_unseededYear_hasNoSessionDaysUntilSeeded() public {
        uint256 jan1 = _refJan1(2029); // Monday, New Year's Day
        // forge-lint: disable-next-line(unsafe-typecast)
        uint32 fri = uint32(jan1 + 4); // Friday 2029-01-05
        // forge-lint: disable-next-line(unsafe-typecast)
        uint40 friClose = uint40(cal.closeOf(fri));
        // forge-lint: disable-next-line(unsafe-typecast)
        uint40 tueClose = uint40(cal.closeOf(uint32(jan1 + 1)));
        // forge-lint: disable-next-line(unsafe-typecast)
        uint40 lastClose2028 = uint40(cal.closeOf(uint32(jan1 - 3))); // Friday 2028-12-29
        uint40 friMidday = friClose - 3 hours; // 13:00 EST, inside the session hours

        assertTrue(cal.isValidExpiry(lastClose2028), "2028 is seeded: its last Friday trades");
        assertTrue(cal.isWeekly(lastClose2028), "and is its week's weekly");
        assertFalse(cal.isValidExpiry(friClose), "unseeded 2029: Friday 01-05 is no expiry");
        assertFalse(cal.isSessionDay(fri), "no session day");
        assertFalse(cal.isWeekly(friClose), "no weekly");
        assertFalse(cal.isRegularSession(friMidday), "no session");
        _expectNoNext(lastClose2028, false);
        _expectNoNext(lastClose2028, true);

        _close(_days(jan1, 1));
        // forge-lint: disable-next-line(unsafe-typecast)
        assertFalse(cal.isValidExpiry(uint40(cal.closeOf(uint32(jan1)))), "New Year's Day itself is closed");
        assertTrue(cal.isValidExpiry(friClose), "seeded 2029: Friday 01-05 trades");
        assertTrue(cal.isSessionDay(fri), "session day");
        assertTrue(cal.isWeekly(friClose), "weekly");
        assertTrue(cal.isRegularSession(friMidday), "in session");
        _expectNext(lastClose2028, false, tueClose, "daily: Tuesday 01-02, over the weekend and New Year's Day");
        _expectNext(lastClose2028, true, friClose, "weekly: Friday 01-05");

        vm.prank(admin);
        cal.setHolidays(_days(jan1, 1), false);
        assertFalse(cal.isValidExpiry(friClose), "removing the year's only closure closes it again");
        assertFalse(cal.isValidExpiry(tueClose), "every weekday of it");
        _expectNoNext(lastClose2028, false);
    }

    /// @dev The count moves only on a real change: a day listed twice, or set to what it already is, counts once, so a
    ///      single removal empties the year. Removing a day that is not set moves nothing and cannot underflow.
    function test_unseededYear_countsChangesNotEntries() public {
        uint256 jan1 = _refJan1(2029);
        // forge-lint: disable-next-line(unsafe-typecast)
        uint40 friClose = uint40(cal.closeOf(uint32(jan1 + 4)));
        uint32[] memory twice = new uint32[](2);
        // forge-lint: disable-next-line(unsafe-typecast)
        (twice[0], twice[1]) = (uint32(jan1), uint32(jan1));
        _close(twice);
        _close(_days(jan1, 1));
        assertTrue(cal.isValidExpiry(friClose), "seeded");

        vm.prank(admin);
        cal.setHolidays(_days(jan1 + 1, 1), false); // not set: no change
        assertTrue(cal.isValidExpiry(friClose), "still seeded");

        vm.prank(admin);
        cal.setHolidays(_days(jan1, 1), false);
        assertFalse(cal.isValidExpiry(friClose), "one removal empties a year seeded by one day, however often listed");
    }

    /// @dev A week that runs into an unseeded year has no weekly: its later weekdays are not known to be closed, so
    ///      they still take the weekly away from the seeded Monday. Seeding the new year then puts the weekly where it
    ///      belongs, rather than moving one that was already handed out.
    function test_unseededYear_weekRunningIntoItHasNoWeekly() public {
        _markSeeded(2029); // 2029 seeded, 2030 not
        uint256 jan1 = _refJan1(2030); // Tuesday
        // forge-lint: disable-next-line(unsafe-typecast)
        uint40 monClose = uint40(cal.closeOf(uint32(jan1 - 1))); // Monday 2029-12-31
        // forge-lint: disable-next-line(unsafe-typecast)
        uint40 friBefore = uint40(cal.closeOf(uint32(jan1 - 4))); // Friday 2029-12-28
        // forge-lint: disable-next-line(unsafe-typecast)
        uint40 friAfter = uint40(cal.closeOf(uint32(jan1 + 3))); // Friday 2030-01-04

        assertTrue(cal.isValidExpiry(monClose), "Monday 12-31 is in seeded 2029");
        assertFalse(cal.isWeekly(monClose), "Tue-Fri of its week are unseeded, not known closed");
        assertFalse(cal.isValidExpiry(friAfter), "Friday 01-04 is in unseeded 2030");
        _expectNext(friBefore, false, monClose, "daily still finds Monday 12-31");
        _expectNoNext(friBefore, true);

        _close(_days(jan1, 1)); // New Year's Day 2030 seeds 2030
        assertFalse(cal.isWeekly(monClose), "Monday is still not the weekly");
        assertTrue(cal.isWeekly(friAfter), "Friday 01-04 is");
        _expectNext(friBefore, true, friAfter, "weekly search lands on it");
    }

    /*//////////////////////////////////////////////////////////////
                              DST WEEKS
    //////////////////////////////////////////////////////////////*/

    /// @dev Spring forward, Sunday 2026-03-08: the close moves from 21:00 to 20:00 UTC between Friday and Monday.
    function test_dst_marchBoundaryWeek2026() public view {
        assertTrue(cal.isValidExpiry(FRI_0306_CLOSE), "Fri 03-06 16:00 EST");
        assertFalse(cal.isValidExpiry(FRI_0306_CLOSE - 1 hours), "Fri 03-06 15:00 EST (20:00 UTC)");
        assertTrue(cal.isWeekly(FRI_0306_CLOSE));
        assertTrue(cal.isValidExpiry(MON_0309_CLOSE), "Mon 03-09 16:00 EDT");
        assertFalse(cal.isValidExpiry(MON_0309_CLOSE + 1 hours), "Mon 03-09 17:00 EDT (21:00 UTC)");
        assertEq(uint256(MON_0309_CLOSE - FRI_0306_CLOSE), 71 hours, "the switch weekend is an hour short");

        assertEq(cal.newYorkOffset(FRI_0306_CLOSE), EST);
        assertEq(cal.newYorkOffset(SUN_0308_0159_59), EST, "01:59:59 EST");
        assertEq(cal.newYorkOffset(SUN_0308_0300), EDT, "one second later it is 03:00:00 EDT");
        assertEq(cal.newYorkOffset(MON_0309_CLOSE), EDT);

        _expectNext(FRI_0306_CLOSE, false, MON_0309_CLOSE, "Fri EST -> Mon EDT");
        _expectNext(FRI_0306_CLOSE, true, FRI_0313_CLOSE, "weekly across the switch");
        _expectNext(SUN_0308_0159_59, false, MON_0309_CLOSE, "from inside the switch night");
        // Monday of the switch week is in session on the EDT clock: 09:30 EDT = 13:30 UTC.
        assertTrue(cal.isRegularSession(MON_0309_CLOSE - 6 hours - 30 minutes), "Mon 09:30 EDT");
        assertFalse(cal.isRegularSession(MON_0309_CLOSE - 6 hours - 30 minutes - 1), "Mon 09:29:59 EDT");
    }

    /// @dev Fall back, Sunday 2026-11-01: the close moves from 20:00 to 21:00 UTC between Friday and Monday.
    function test_dst_novemberBoundaryWeek2026() public view {
        assertTrue(cal.isValidExpiry(FRI_1030_CLOSE), "Fri 10-30 16:00 EDT");
        assertFalse(cal.isValidExpiry(FRI_1030_CLOSE + 1 hours), "Fri 10-30 17:00 EDT (21:00 UTC)");
        assertTrue(cal.isWeekly(FRI_1030_CLOSE));
        assertTrue(cal.isValidExpiry(MON_1102_CLOSE), "Mon 11-02 16:00 EST");
        assertFalse(cal.isValidExpiry(MON_1102_CLOSE - 1 hours), "Mon 11-02 15:00 EST (20:00 UTC)");
        assertEq(uint256(MON_1102_CLOSE - FRI_1030_CLOSE), 73 hours, "the switch weekend is an hour long");

        assertEq(cal.newYorkOffset(FRI_1030_CLOSE), EDT);
        assertEq(cal.newYorkOffset(SUN_1101_0159_59), EDT, "01:59:59 EDT");
        assertEq(cal.newYorkOffset(SUN_1101_0100_EST), EST, "one second later it is 01:00:00 EST");
        assertEq(cal.newYorkOffset(MON_1102_CLOSE), EST);

        _expectNext(FRI_1030_CLOSE, false, MON_1102_CLOSE, "Fri EDT -> Mon EST");
        _expectNext(FRI_1030_CLOSE, true, FRI_1106_CLOSE, "weekly across the switch");
        assertTrue(cal.isRegularSession(MON_1102_CLOSE - 1), "Mon 15:59:59 EST");
        assertFalse(cal.isRegularSession(MON_1102_CLOSE), "Mon 16:00:00 EST");
    }

    /*//////////////////////////////////////////////////////////////
                         NON-CLOSE INSTANTS
    //////////////////////////////////////////////////////////////*/

    function test_validExpiry_rejectsEverythingButTheCloseSecond() public view {
        uint40[8] memory near = [
            FRI_0918_CLOSE - 1,
            FRI_0918_CLOSE + 1,
            FRI_0918_CLOSE - 60,
            FRI_0918_CLOSE + 60,
            FRI_0918_CLOSE - 1 hours, // 15:00 EDT
            FRI_0918_CLOSE + 1 hours, // 17:00 EDT, the EST close instant on an EDT date
            FRI_0918_CLOSE - 20 hours, // 00:00 UTC
            FRI_0918_CLOSE - 4 hours // 12:00 EDT
        ];
        assertTrue(cal.isValidExpiry(FRI_0918_CLOSE));
        for (uint256 i; i < near.length; ++i) {
            assertFalse(cal.isValidExpiry(near[i]), vm.toString(uint256(near[i])));
            assertFalse(cal.isWeekly(near[i]), vm.toString(uint256(near[i])));
        }
        assertFalse(cal.isValidExpiry(WED_1202_CLOSE - 1 hours), "Wed 12-02 15:00 EST, the EDT close instant");
        assertFalse(cal.isValidExpiry(0));
        assertFalse(cal.isValidExpiry(type(uint40).max));
    }

    function test_validExpiry_weekendClosesRejected() public view {
        assertFalse(cal.isValidExpiry(SAT_0919_1600), "Sat 16:00 EDT");
        assertFalse(cal.isValidExpiry(SAT_0919_1600 + 1 days), "Sun 16:00 EDT");
        assertFalse(cal.isWeekly(SAT_0919_1600));
        assertTrue(cal.isValidExpiry(MON_0921_CLOSE));
    }

    /*//////////////////////////////////////////////////////////////
                                WEEKLY
    //////////////////////////////////////////////////////////////*/

    function test_weekly_fridayHolidayMovesToThursday() public view {
        assertFalse(cal.isValidExpiry(GOOD_FRI_0403_CLOSE), "Good Friday 2026 is closed");
        assertFalse(cal.isWeekly(GOOD_FRI_0403_CLOSE));
        assertTrue(cal.isWeekly(THU_0402_CLOSE), "Thursday takes the weekly");
        assertFalse(cal.isWeekly(THU_0402_CLOSE - 1 days), "Wednesday does not");
        _expectNext(THU_0402_CLOSE - 1 days, true, THU_0402_CLOSE, "weekly search lands on Thursday");
        _expectNext(THU_0402_CLOSE, false, MON_0406_CLOSE, "daily skips the holiday and the weekend");

        // Christmas 2026 and New Year 2027 are both Fridays: two Thursday weeklies in a row.
        assertTrue(cal.isWeekly(THU_1224_CLOSE));
        assertTrue(cal.isWeekly(THU_1231_CLOSE));
        assertFalse(cal.isWeekly(CHRISTMAS_1225_CLOSE));
        assertFalse(cal.isWeekly(NEW_YEAR_0101_CLOSE));
    }

    function test_weekly_thursdayAndFridayClosedMovesToWednesday() public {
        assertTrue(cal.isWeekly(THU_0702_CLOSE), "seeded: Friday 07-03 closed, Thursday weekly");
        _close(_days(_day(THU_0702_CLOSE), 1));
        assertFalse(cal.isWeekly(THU_0702_CLOSE));
        assertTrue(cal.isWeekly(WED_0701_CLOSE), "Wednesday is now the last session of the week");
        _expectNext(WED_0701_CLOSE - 1, true, WED_0701_CLOSE, "weekly");
        _expectNext(WED_0701_CLOSE, false, MON_0706_CLOSE, "daily skips Thu, Fri and the weekend");
        _expectNext(WED_0701_CLOSE, true, FRI_0710_CLOSE, "9 days to the next weekly");
    }

    /// @dev A week with no session has no weekly; the search crosses it and the bound is inclusive.
    function test_weekly_closedWeekHasNoWeeklyAndSearchBoundIsInclusive() public {
        _close(_days(MONDAY_2026_09_21, 5));
        for (uint40 ts = MON_0921_CLOSE; ts <= FRI_0925_CLOSE; ts += 1 days) {
            assertFalse(cal.isValidExpiry(ts));
            assertFalse(cal.isWeekly(ts));
        }
        _expectNext(FRI_0918_CLOSE, false, MON_0928_CLOSE, "daily crosses the closed week");
        assertEq(uint256(FRI_1002_CLOSE - FRI_0918_CLOSE), 14 days);
        _expectNext(FRI_0918_CLOSE, true, FRI_1002_CLOSE, "exactly afterTs + 14 days is inside the search");
        _expectNext(FRI_0918_CLOSE - 1, true, FRI_0918_CLOSE, "strictly-after still finds the Friday itself");

        // Close the following week too: the next weekly (10-09) is 21 days out.
        _close(_days(MONDAY_2026_09_21 + 7, 5));
        _expectNoNext(FRI_0918_CLOSE, true);
        _expectNoNext(FRI_0918_CLOSE, false);
        _expectNext(FRI_0918_CLOSE + 7 days, true, FRI_1009_CLOSE, "later searches resume past the gap");
    }

    /*//////////////////////////////////////////////////////////////
                              NEXT EXPIRY
    //////////////////////////////////////////////////////////////*/

    function test_nextExpiry_weekendAndStrictlyAfter() public view {
        _expectNext(FRI_0918_CLOSE, false, MON_0921_CLOSE, "Fri close -> Mon close");
        _expectNext(FRI_0918_CLOSE - 1, false, FRI_0918_CLOSE, "one second before the close -> that close");
        _expectNext(SAT_0919_NOON, false, MON_0921_CLOSE, "Saturday -> Monday");
        _expectNext(SAT_0919_NOON, true, FRI_0925_CLOSE, "Saturday -> next Friday");
        _expectNext(FRI_0918_CLOSE, true, FRI_0925_CLOSE, "Fri close -> next Fri close");
        _expectNext(WED_0916_0930, false, WED_0916_CLOSE, "in session -> today's close");
        _expectNext(WED_0916_CLOSE, true, FRI_0918_CLOSE, "Wed close -> Fri weekly");
    }

    function test_nextExpiry_thanksgiving2026() public view {
        _expectNext(WED_1125_CLOSE, false, FRI_1127_CLOSE, "Wed close skips Thanksgiving to the early-close Friday");
        _expectNext(THANKSGIVING_1126_NOON, false, FRI_1127_CLOSE, "from Thanksgiving itself");
        _expectNext(TUE_1124_0900, false, TUE_1124_CLOSE, "Tuesday morning -> Tuesday close");
        _expectNext(MON_1123_CLOSE, true, FRI_1127_CLOSE, "the Friday after Thanksgiving is the weekly");
        _expectNext(FRI_1127_CLOSE, true, WED_1202_CLOSE + 2 days, "then the next Friday, 12-04");
    }

    function test_nextExpiry_christmasToNewYear2026() public view {
        _expectNext(THU_1224_CLOSE - 1 days, false, THU_1224_CLOSE, "Wed 12-23 -> Christmas Eve");
        _expectNext(THU_1224_CLOSE, false, MON_1228_CLOSE, "Christmas Eve -> Monday over Christmas and the weekend");
        _expectNext(THU_1224_CLOSE, true, THU_1231_CLOSE, "Thursday weekly -> Thursday weekly");
        _expectNext(THU_1231_CLOSE, false, MON_0104_CLOSE, "New Year Eve -> Monday over New Year and the weekend");
        _expectNext(THU_1231_CLOSE, true, FRI_0108_CLOSE, "-> first full week of 2027");
        _expectNext(CHRISTMAS_1225_CLOSE, true, THU_1231_CLOSE, "from Christmas itself");
    }

    function test_nextExpiry_christmasToNewYear2027() public view {
        assertFalse(cal.isValidExpiry(FRI_2027_1224_CLOSE), "Christmas observed on Friday 12-24");
        assertTrue(cal.isWeekly(THU_2027_1223_CLOSE));
        _expectNext(THU_2027_1223_CLOSE, false, MON_2027_1227_CLOSE, "Thu -> Mon over the observed holiday");
        _expectNext(THU_2027_1223_CLOSE, true, FRI_2027_1231_CLOSE, "New Year 2028 is a Saturday: 12-31 trades");
        _expectNext(FRI_2027_1231_CLOSE, false, MON_2028_0103_CLOSE, "-> first session of 2028");
    }

    /// @dev Past the last representable close the search reverts with the shared error, never an overflow panic.
    function test_nextExpiry_nearUint40MaxReverts() public {
        _expectNoNext(type(uint40).max, false);
        _expectNoNext(type(uint40).max, true);
        _expectNoNext(type(uint40).max - 1 hours, false);
    }

    /*//////////////////////////////////////////////////////////////
                           REGULAR SESSION
    //////////////////////////////////////////////////////////////*/

    function test_regularSession_edgesInEdtAndEst() public view {
        assertFalse(cal.isRegularSession(WED_0916_0929_59), "EDT 09:29:59");
        assertTrue(cal.isRegularSession(WED_0916_0930), "EDT 09:30:00");
        assertTrue(cal.isRegularSession(WED_0916_1559_59), "EDT 15:59:59");
        assertFalse(cal.isRegularSession(WED_0916_CLOSE), "EDT 16:00:00");

        assertFalse(cal.isRegularSession(WED_1202_0929_59), "EST 09:29:59");
        assertTrue(cal.isRegularSession(WED_1202_0930), "EST 09:30:00");
        assertTrue(cal.isRegularSession(WED_1202_1559_59), "EST 15:59:59");
        assertFalse(cal.isRegularSession(WED_1202_CLOSE), "EST 16:00:00");

        // The EDT session instants shifted by an hour are outside the EST session and vice versa.
        assertFalse(cal.isRegularSession(WED_1202_0930 - 1 hours), "EST 08:30");
        assertFalse(cal.isRegularSession(WED_0916_1559_59 + 1 hours), "EDT 16:59:59");
    }

    function test_regularSession_weekendHolidayAndEarlyClose() public view {
        assertFalse(cal.isRegularSession(SAT_0919_NOON), "Saturday noon");
        assertFalse(cal.isRegularSession(SAT_0919_NOON + 1 days), "Sunday noon");
        assertFalse(cal.isRegularSession(THANKSGIVING_1126_NOON), "Thanksgiving noon");
        assertFalse(cal.isRegularSession(GOOD_FRI_0403_CLOSE - 5 hours), "Good Friday 11:00");
        assertTrue(cal.isRegularSession(FRI_1127_1400), "early-close day at 14:00 still counts (ADR-07)");
    }

    /*//////////////////////////////////////////////////////////////
                           SPECIAL EXPIRIES
    //////////////////////////////////////////////////////////////*/

    function test_special_acceptedButNeverWeeklyNorReturned() public {
        vm.expectEmit(address(cal));
        emit IExpiryCalendar.SpecialExpirySet(FRI_0918_NOON, true);
        vm.prank(admin);
        cal.setSpecialExpiry(FRI_0918_NOON, true);

        assertTrue(cal.specialExpiry(FRI_0918_NOON));
        assertTrue(cal.isValidExpiry(FRI_0918_NOON), "whitelisted Friday noon is a valid expiry");
        assertFalse(cal.isWeekly(FRI_0918_NOON), "a special expiry is never weekly");
        assertTrue(cal.isWeekly(FRI_0918_CLOSE), "an earlier special expiry does not take the weekly from the close");
        _expectNext(FRI_0918_NOON - 1, false, FRI_0918_CLOSE, "nextExpiry reads the grid only");
        _expectNext(FRI_0918_CLOSE, false, MON_0921_CLOSE, "and skips nothing after it");
    }

    /// @dev T-479 (BUG-04 F3). The report's witness: Sunday 16:00 has no session, so the Chainlink source's round in
    ///      force at the window start is Friday's last print, over `maxStale` old, and on a Chainlink-only market no
    ///      source is ever ok. Refused at the calendar, before any series can be created on it. The edges pin the
    ///      rule: the whole window [ts - SETTLEMENT_WINDOW, ts] inside one session, in daylight and standard time.
    ///      PROVE BY BREAKING: remove the check in {ExpiryCalendar.setSpecialExpiry} and this test goes red.
    function test_special_refusesAnInstantNoSessionCanPrice() public {
        uint40[7] memory refused = [
            SUN_0920_1600, SAT_0919_NOON, GOOD_FRI_0403_CLOSE, WED_0916_0959_59, WED_0916_1600_01, WED_1202_0959_59, 1
        ];
        for (uint256 i; i < refused.length; ++i) {
            vm.prank(admin);
            vm.expectRevert(V2Errors.BadExpiry.selector);
            cal.setSpecialExpiry(refused[i], true);
            assertFalse(cal.isValidExpiry(refused[i]), "a refused instant stays invalid");
        }

        uint40[4] memory accepted = [WED_0916_1000, FRI_0918_NOON, WED_1202_1000, WED_0916_CLOSE];
        for (uint256 i; i < accepted.length; ++i) {
            vm.prank(admin);
            cal.setSpecialExpiry(accepted[i], true);
            assertTrue(cal.specialExpiry(accepted[i]), "a window inside one session is accepted");
        }
    }

    function test_special_onHolidayIsRefusedAndTheWeeklyStays() public {
        vm.prank(admin);
        vm.expectRevert(V2Errors.BadExpiry.selector);
        cal.setSpecialExpiry(GOOD_FRI_0403_CLOSE, true);

        assertFalse(cal.isValidExpiry(GOOD_FRI_0403_CLOSE), "the Good Friday close is not a valid expiry");
        assertTrue(cal.isWeekly(THU_0402_CLOSE), "Thursday keeps the weekly");
        _expectNext(THU_0402_CLOSE, false, MON_0406_CLOSE, "not returned by nextExpiry");
        _expectNext(THU_0402_CLOSE - 1 days, true, THU_0402_CLOSE, "weekly search unchanged");
    }

    function test_special_removalAndRegularCloses() public {
        vm.startPrank(admin);
        cal.setSpecialExpiry(FRI_0918_NOON, true);
        cal.setSpecialExpiry(WED_0916_CLOSE, true);

        vm.expectEmit(address(cal));
        emit IExpiryCalendar.SpecialExpirySet(FRI_0918_NOON, false);
        cal.setSpecialExpiry(FRI_0918_NOON, false);
        cal.setSpecialExpiry(WED_0916_CLOSE, false);

        // Removal is never refused, even for an instant the rule would not accept today: one whitelisted before the
        // rule existed must still come off.
        vm.expectEmit(address(cal));
        emit IExpiryCalendar.SpecialExpirySet(SUN_0920_1600, false);
        cal.setSpecialExpiry(SUN_0920_1600, false);
        vm.stopPrank();

        assertFalse(cal.isValidExpiry(FRI_0918_NOON), "removed special is invalid again");
        assertTrue(cal.isValidExpiry(WED_0916_CLOSE), "a grid close stays valid whatever its special flag");
        assertFalse(cal.isValidExpiry(SUN_0920_1600));
    }

    /*//////////////////////////////////////////////////////////////
                                 ADMIN
    //////////////////////////////////////////////////////////////*/

    function test_admin_settersAreAdminOnly() public {
        uint32[] memory one = _days(_day(WED_0916_CLOSE), 1);

        vm.prank(alice);
        vm.expectRevert(V2Errors.NotAuthorized.selector);
        cal.setHolidays(one, true);

        vm.prank(alice);
        vm.expectRevert(V2Errors.NotAuthorized.selector);
        cal.setSpecialExpiry(SAT_0919_NOON, true);

        vm.prank(alice);
        vm.expectRevert(V2Errors.NotAuthorized.selector);
        cal.setAuthority(alice);

        assertTrue(cal.isValidExpiry(WED_0916_CLOSE));
        assertFalse(cal.isValidExpiry(SAT_0919_NOON));
    }

    function test_admin_setHolidaysAddsAndRemovesWithEvents() public {
        uint32[] memory week = _days(MONDAY_2026_09_21, 5);

        for (uint256 i; i < week.length; ++i) {
            vm.expectEmit(address(cal));
            emit IExpiryCalendar.HolidaySet(week[i], true);
        }
        vm.prank(admin);
        cal.setHolidays(week, true);
        assertFalse(cal.isValidExpiry(MON_0921_CLOSE));
        assertTrue(cal.holiday(week[4]));

        vm.expectEmit(address(cal));
        emit IExpiryCalendar.HolidaySet(week[0], false);
        vm.prank(admin);
        cal.setHolidays(_days(MONDAY_2026_09_21, 1), false);
        assertTrue(cal.isValidExpiry(MON_0921_CLOSE), "reopened");
        assertFalse(cal.isValidExpiry(MON_0921_CLOSE + 1 days), "the rest stay closed");

        // Removing a seeded holiday reopens it.
        uint32[] memory goodFriday = _days(_day(GOOD_FRI_0403_CLOSE), 1);
        vm.prank(admin);
        cal.setHolidays(goodFriday, false);
        assertTrue(cal.isWeekly(GOOD_FRI_0403_CLOSE));
        assertFalse(cal.isWeekly(THU_0402_CLOSE));
    }

    function test_admin_grantedAdminCanMaintain() public {
        _grant(V8Roles.LISTING, bob, 0);
        vm.prank(bob);
        cal.setSpecialExpiry(FRI_0918_NOON, true);
        assertTrue(cal.isValidExpiry(FRI_0918_NOON));

        manager.revokeRole(V8Roles.LISTING, bob);
        vm.prank(bob);
        vm.expectRevert(V2Errors.NotAuthorized.selector);
        cal.setSpecialExpiry(FRI_0918_NOON, false);
    }

    /*//////////////////////////////////////////////////////////////
                                 FUZZ
    //////////////////////////////////////////////////////////////*/

    /// @dev Any valid expiry is a Monday-Friday non-holiday 16:00:00 New York; on a session day exactly one of the two
    ///      candidate UTC instants (20:00, 21:00) is valid, on other days neither. Whole uint40 range, seeded holidays;
    ///      outside the seeded 2026-2028 no day is a session day (SEC-48).
    function testFuzz_validExpiryIsWeekdayClose(uint256 dayRaw, uint256 secondRaw) public view {
        uint256 day = bound(dayRaw, 0, DAY_MAX - 1);
        uint256 ts = day * DAY + bound(secondRaw, 0, DAY - 1);
        // forge-lint: disable-next-line(unsafe-typecast)
        uint40 t = uint40(ts);
        // forge-lint: disable-next-line(unsafe-typecast)
        bool session = _refWeekday(day) < 5 && !cal.holiday(uint32(day)) && _refSeeded(day);

        if (cal.isValidExpiry(t)) {
            assertLt(_refWeekday(day), 5, "valid expiry on a weekend");
            assertTrue(session, "valid expiry on a holiday");
            uint256 behindUtc = cal.newYorkOffset(t) == EDT ? 4 hours : 5 hours;
            assertEq((ts - behindUtc) % DAY, 16 hours, "valid expiry is not 16:00:00 New York");
        }

        // forge-lint: disable-next-line(unsafe-typecast)
        uint40 at20 = uint40(day * DAY + 20 hours);
        // forge-lint: disable-next-line(unsafe-typecast)
        uint40 at21 = uint40(day * DAY + 21 hours);
        uint256 hits = (cal.isValidExpiry(at20) ? 1 : 0) + (cal.isValidExpiry(at21) ? 1 : 0);
        assertEq(hits, session ? 1 : 0, "one close per session day");
        // forge-lint: disable-next-line(unsafe-typecast)
        assertEq(cal.isSessionDay(uint32(day)), session);
    }

    /// @dev Matches the closed-form DST rule to the second over 2007-2099.
    /// @dev T-479. {setSpecialExpiry} accepts `ts` exactly when the window start is in a regular session and the
    ///      window end is too, or is that session's close - cross-checked against {isRegularSession} and the grid, an
    ///      implementation this rule does not share. Bounded to the seeded years 2026-2028.
    function testFuzz_special_acceptedExactlyWhenTheWindowIsInOneSession(uint256 tsRaw) public {
        // casting to uint40 is safe because the bound is below 2^40
        // forge-lint: disable-next-line(unsafe-typecast)
        uint40 ts = uint40(bound(tsRaw, 1_767_225_600, 1_861_919_999)); // 2026-01-01 .. 2028-12-31 UTC
        uint40 start = ts - 1800;
        bool gridClose = cal.isValidExpiry(ts); // no special is set yet, so this is the grid alone
        bool expected = cal.isRegularSession(start) && (cal.isRegularSession(ts) || gridClose);
        vm.prank(admin);
        if (!expected) vm.expectRevert(V2Errors.BadExpiry.selector);
        cal.setSpecialExpiry(ts, true);
        assertEq(cal.specialExpiry(ts), expected);
    }

    function testFuzz_newYorkOffsetMatchesReference(uint256 tsRaw) public view {
        uint256 ts = bound(tsRaw, DAY_2007 * DAY, DAY_2100 * DAY - 1);
        // forge-lint: disable-next-line(unsafe-typecast)
        assertEq(cal.newYorkOffset(uint40(ts)), _refOffset(ts));
    }

    /// @dev The two DST switch instants of a fuzzed year, to the second.
    function testFuzz_newYorkOffsetSwitchInstants(uint256 yearRaw) public view {
        uint256 year = bound(yearRaw, 2007, 2099);
        uint256 k = (1 + year * 5 / 4) % 7;
        uint256 leap = _refIsLeap(year) ? 1 : 0;
        uint256 start = (_refJan1(year) + 59 + leap + (14 - k) - 1) * DAY + 7 hours;
        uint256 end = (_refJan1(year) + 304 + leap + (7 - k) - 1) * DAY + 6 hours;
        assertEq(_refWeekday(start / DAY), 6, "spring switch is a Sunday");
        assertEq(_refWeekday(end / DAY), 6, "fall switch is a Sunday");
        // forge-lint: disable-next-line(unsafe-typecast)
        assertEq(cal.newYorkOffset(uint40(start - 1)), EST);
        // forge-lint: disable-next-line(unsafe-typecast)
        assertEq(cal.newYorkOffset(uint40(start)), EDT);
        // forge-lint: disable-next-line(unsafe-typecast)
        assertEq(cal.newYorkOffset(uint40(end - 1)), EDT);
        // forge-lint: disable-next-line(unsafe-typecast)
        assertEq(cal.newYorkOffset(uint40(end)), EST);
    }

    /// @dev Never reverts and never returns anything but the two offsets, over the whole uint40 range.
    function testFuzz_newYorkOffsetIsEdtOrEst(uint40 ts) public view {
        int32 off = cal.newYorkOffset(ts);
        assertTrue(off == EDT || off == EST);
    }

    /// @dev Over 2007-2099 the session is exactly [09:30, 16:00) New York on a Mon-Fri non-holiday of a seeded year,
    ///      per the reference.
    function testFuzz_regularSessionMatchesReference(uint256 tsRaw) public view {
        uint256 ts = bound(tsRaw, DAY_2007 * DAY, DAY_2100 * DAY - 1);
        uint256 local = ts - (_refOffset(ts) == EDT ? 4 hours : 5 hours);
        uint256 day = local / DAY;
        uint256 second = local % DAY;
        // forge-lint: disable-next-line(unsafe-typecast)
        bool closed = cal.holiday(uint32(day)) || !_refSeeded(day);
        bool expected = _refWeekday(day) < 5 && !closed && second >= 9 hours + 30 minutes && second < 16 hours;
        // forge-lint: disable-next-line(unsafe-typecast)
        assertEq(cal.isRegularSession(uint40(ts)), expected);
    }

    /// @dev Over 2007-2099 every session day's close is the reference 16:00 New York instant.
    function testFuzz_closeMatchesReference(uint256 dayRaw) public view {
        uint256 day = bound(dayRaw, DAY_2007, DAY_2100 - 1);
        // forge-lint: disable-next-line(unsafe-typecast)
        assertEq(cal.closeOf(uint32(day)), _refClose(day));
    }

    /// @dev nextExpiry(t) > t, lands on a valid Mon-Fri close within 14 days (weekly when asked), and skips nothing.
    ///      2025-2031 covers the seeded holidays and the year boundaries around them. The years outside the launch seed
    ///      are marked seeded (a Saturday closure each) so the search runs across them: closing them is SEC-48's
    ///      behaviour, pinned by the test_unseededYear_* tests, not this one's subject.
    function testFuzz_nextExpiryIsNextValidClose(uint256 tsRaw, bool weekly) public {
        _markSeeded(2025);
        for (uint256 year = 2029; year <= 2031; ++year) {
            _markSeeded(year);
        }
        uint256 ts = bound(tsRaw, _refJan1(2025) * DAY, _refJan1(2031) * DAY);
        // forge-lint: disable-next-line(unsafe-typecast)
        uint40 t = uint40(ts);
        uint40 e = cal.nextExpiry(t, weekly);

        assertGt(e, t, "nextExpiry(t) > t");
        assertLe(uint256(e), ts + 14 days, "inside the search bound");
        assertTrue(cal.isValidExpiry(e), "valid");
        assertLt(_refWeekday(e / DAY), 5, "Mon-Fri");
        if (weekly) assertTrue(cal.isWeekly(e), "weekly when asked");

        for (uint256 day = ts / DAY; day <= e / DAY; ++day) {
            uint256 c = _refClose(day);
            if (c <= ts || c >= e) continue;
            // forge-lint: disable-next-line(unsafe-typecast)
            uint40 skipped = uint40(c);
            assertFalse(weekly ? cal.isWeekly(skipped) : cal.isValidExpiry(skipped), "skipped an earlier expiry");
        }
    }

    /// @dev Over the whole uint40 range nextExpiry either returns something later or reverts BadExpiry, and it reverts
    ///      exactly when no close of the seeded 2026-2028 lies in (t, t + 14 days]: from Friday 2028-12-29, the last
    ///      2028 close and weekly, onward (the end of uint40 included), and before Friday 2026-01-02, the first.
    ///      SEC-48: before it, this test allowed a revert only in the last two weeks of the range.
    function testFuzz_nextExpiryAnyTs(uint40 t, bool weekly) public view {
        uint256 firstSeeded = _refClose(_refJan1(2026) + 1);
        uint256 lastSeeded = _refClose(_refJan1(2029) - 3);
        try cal.nextExpiry(t, weekly) returns (uint40 e) {
            assertGt(e, t, "nextExpiry(t) > t");
            assertTrue(cal.isValidExpiry(e));
            assertLt(_refWeekday(e / DAY), 5, "Mon-Fri");
            assertTrue(uint256(e) >= firstSeeded && uint256(e) <= lastSeeded, "a close outside the seeded years");
        } catch (bytes memory err) {
            assertEq(err, abi.encodeWithSelector(V2Errors.BadExpiry.selector));
            assertTrue(
                uint256(t) >= lastSeeded || uint256(t) + 14 days < firstSeeded,
                "reverted with a seeded close inside the search"
            );
        }
    }

    /// @dev With any subset of a week's weekdays closed, the weekly is the last open weekday (none when all are
    ///      closed), and both searches from the week's start agree. Weeks after 2030 up to the end of uint40, where
    ///      no seeded holiday interferes. Those years have no closure, so the Saturdays before, of and after the week
    ///      are closed first: that seeds every year the week and the next one touch (SEC-48) and no weekday read sees
    ///      it, so the week tests the weekly rule and not the unseeded-year one.
    function testFuzz_weeklyIsLastOpenWeekday(uint256 weekRaw, uint8 closedMask) public {
        uint256 monday = MONDAY_2026_09_21 + 7 * bound(weekRaw, 250, (DAY_MAX - MONDAY_2026_09_21) / 7 - 3);
        _close(_days(monday - 2, 1));
        _close(_days(monday + 5, 1));
        _close(_days(monday + 12, 1));
        uint256 lastOpen = type(uint256).max;
        uint256 firstOpen = type(uint256).max;
        for (uint256 i; i < 5; ++i) {
            if ((closedMask >> i) & 1 == 1) {
                _close(_days(monday + i, 1));
            } else {
                lastOpen = i;
                if (firstOpen == type(uint256).max) firstOpen = i;
            }
        }

        for (uint256 i; i < 7; ++i) {
            // forge-lint: disable-next-line(unsafe-typecast)
            uint40 c = uint40(cal.closeOf(uint32(monday + i)));
            bool open = i < 5 && (closedMask >> i) & 1 == 0;
            assertEq(cal.isValidExpiry(c), open, "valid iff an open weekday");
            assertEq(cal.isWeekly(c), open && i == lastOpen, "weekly iff the last open weekday");
        }

        // forge-lint: disable-next-line(unsafe-typecast)
        uint40 weekStart = uint40(monday * DAY);
        // forge-lint: disable-next-line(unsafe-typecast)
        uint40 nextMonday = uint40(cal.closeOf(uint32(monday + 7)));
        // forge-lint: disable-next-line(unsafe-typecast)
        uint40 nextFriday = uint40(cal.closeOf(uint32(monday + 11)));
        uint40 daily = cal.nextExpiry(weekStart, false);
        uint40 weeklyNext = cal.nextExpiry(weekStart, true);
        if (lastOpen == type(uint256).max) {
            assertEq(daily, nextMonday, "closed week: daily is next Monday");
            assertEq(weeklyNext, nextFriday, "closed week: weekly is next Friday");
        } else {
            // forge-lint: disable-next-line(unsafe-typecast)
            assertEq(uint256(daily), cal.closeOf(uint32(monday + firstOpen)), "daily is the first open weekday");
            // forge-lint: disable-next-line(unsafe-typecast)
            assertEq(uint256(weeklyNext), cal.closeOf(uint32(monday + lastOpen)), "weekly is the last open weekday");
        }
    }
}
