// SPDX-License-Identifier: MIT
pragma solidity 0.8.28;

import {Test} from "forge-std/Test.sol";
import {Policy} from "../../src/Policy.sol";

/// @notice Differential check: the keeper's TypeScript premium split must agree with the
///         on-chain one for every input, or the vault rejects the very order the keeper posts.
/// @dev The vectors are generated by the same LCG as scripts used in keeper development; the
///      point is that both sides floor the fee PER CONTRACT and then multiply.
contract SplitDiffTest is Test {
    function _lcg(uint256 s) internal pure returns (uint256) {
        unchecked {
            return (s * 6364136223846793005 + 1442695040888963407) % (2 ** 64);
        }
    }

    function test_splitMatchesTheKeeperVectors() public pure {
        uint256 seed = 12345;
        for (uint256 i; i < 40; i++) {
            seed = _lcg(seed);
            uint256 u = 20 + (seed % 50_000_000);
            seed = _lcg(seed);
            uint256 n = 1 + (seed % 50);

            (uint256 toVault, uint256 toOvercall, uint256 gross) = Policy.splitPremium(u, n);

            // The properties the keeper relies on, asserted directly.
            assertEq(toVault + toOvercall, gross, "split is lossless");
            assertEq(gross, u * n, "gross is unit x contracts");
            assertEq(toVault % n, 0, "consideration[0] divides by the order size");
            assertEq(toOvercall % n, 0, "consideration[1] divides by the order size");
            assertEq(toOvercall, ((u * 500) / 10_000) * n, "fee floors per contract, then multiplies");
        }
    }

    /// @dev The same properties over the whole realistic input space.
    function testFuzz_splitIsAlwaysFillable(uint256 u, uint256 n) public pure {
        u = bound(u, 20, 1e12);
        n = bound(n, 1, 1_000);
        (uint256 toVault, uint256 toOvercall, uint256 gross) = Policy.splitPremium(u, n);
        assertEq(toVault + toOvercall, gross);
        assertEq(toVault % n, 0, "a PARTIAL_OPEN order Seaport can actually fill in fractions");
        assertEq(toOvercall % n, 0);
        assertGt(toOvercall, 0, "Overcall's consideration item is never zero above the floor");
    }
}
